### PR TITLE
Declare extern functions in separate headers

### LINKED ISSUE #72: ftbfs with gcc 10
it fails to build with gcc>=10 as now it default to -fno-common:
```
/usr/sbin/ld: CMakeFiles/libmmg_so.dir/src/mmg2d/anisosiz_2d.c.o:(.bss+0x30): multiple definition of `MMG5_renumbering'; CMakeFiles/libmmg_so.dir/src/common/mmgexterns.c.o:(.bss+0x0): first defined here
/usr/sbin/ld: CMakeFiles/libmmg_so.dir/src/mmg2d/anisosiz_2d.c.o:(.bss+0x38): multiple definition of `MMG5_compute_meanMetricAtMarkedPoints'; CMakeFiles/libmmg_so.dir/src/common/mmgexterns.c.o:(.bss+0x8): first defined here             
/usr/sbin/ld: CMakeFiles/libmmg_so.dir/src/mmg2d/anisosiz_2d.c.o:(.bss+0x40): multiple definition of `MMG5_grad2metreq_ani'; CMakeFiles/libmmg_so.dir/src/common/mmgexterns.c.o:(.bss+0x10): first defined here
...
```

### PR DESCRIPTION
**Pull request by xantares**
I hope it fixes the build on clang this time

Closes #72

cc @prj-

### CODE REVIEW

**Comment by Algiane** [comment]
Hi @xantares,

Thanks for your contribution but it still gives me the same undefined symbols on catalina.

**Comment by xantares** [comment]
the idea is to declare extern everywhere in mmg*extern.h and include mmg*extern.c with the actual declaration only once.

**Comment by Algiane** [comment]
I have added the initialisation of the function pointers in the branch `PR/xantares-extern`.
It allows to build with clang with and without the -fno-common flag. Can you please confirm me that it works under gcc>=10 too?

thank you by advance,

**Comment by xantares** [comment]
yes, it still builds fine

**Comment by Algiane** [comment]
Thanks,

so I will merge this into the master, cross my fingers and close the #73 and #72 pull requests.

Have a nice day.
Algiane

**Pull request closed without merging**
