### PR TITLE
Add support for custom Isosurface boundary label

### PR DESCRIPTION
**Pull request by cbritopacheco**
See #118 .

### CODE REVIEW

**Comment by cbritopacheco** [comment]
I have tested this locally and it seems to work without any problems. The default `isoref` is still 10 and you may test this by setting a different value like so:

```
int mycustomisoref = 42;
MMG2D_Set_iparameter(mesh, sol, MMG2D_IPARAM_isoref, 42);
```

**Comment by Algiane** [comment]
I have added the CLI and continuous integration test cases:
  - if bash is not detected (most likely on windows), we only check that the tests are running without errors;
  - otherwise, 2 similar tests cases are run:
      - the first one starts with an already discretized isovalue that has the MG_ISO reference and tries to discretize a new MG_ISO value;
       - the other one  starts with an already discretized isovalue that has the `isoref=5` reference and tries to discretize a new `isoref=5` value;
       - both tests must return the same final mesh with different references for the isovalue. As nor the output files, nor the terminal outputs can be directly compared (due to clock prints in the terminal outputs), we check that we have probably the same output file by comparing lines and words count.
       
As a reminder : for mmg2d, results of both tests are similar even without cleaning the old discretization of the isovalue (probably because removing the domain ref leads to remove the edges of the interface). It is not the case in mmgs and mmg3d, in which, discretizing the isoref 5 on a mesh that contains an isovalue `MG_ISO` leads to different results than  discretizing the isoref 5 on a mesh that contains an isovalue of reference `5`.

**Comment by Algiane** [comment]
Hi again,

I have also changed the target branch of the PR: I prefer to merge it inside the develop branch so this new feature will be integrated inside the master branch in the next release.

Best Regards

**Comment by Algiane** [comment]
And thanks again for your contribution (the rush makes me forget the politeness 😅)!

**Comment by cbritopacheco** [comment]
Hi Algiane, thanks for merging the pull request! It will certainly be useful (at least for me) in your next release :)

Thanks again,
Carlos.

**Pull request merged**
