### PR TITLE
Feature/aniso unit tensor

### PR DESCRIPTION
**Pull request by Algiane**
Improvement of  `-optim -A` mode
=========================
Adding of the possibility to preserve input edge length (so to improve a mesh) for an anisotropic input mesh using the `-optim -A` option combination.

Before this PR, on each node, the average length of the edges passing through the node was computed and this (isotropic) length was imposed as an anisotropic tensor. The input anisotropy of the mesh was therefore not preserved.

Now, the anisotropic metric is constructed by the computation of the length distribution tensor (see [_**T. Coupez**_,
**Metric construction by length distribution tensor and edge based error for anisotropic adaptive meshing**](https://www.sciencedirect.com/science/article/pii/S002199911000656X)).

For the 3 Mmg codes, comparison between input mesh (left), old behaviour (middle) and new behaviour (right) are provided in the following examples (tests are running with disabled gradation).

# Mmg2d
Capture d’écran 2022-08-24 à 10 54 28

# Mmgs

In general, we can't compute directly the 3D tensor at a node: if all the element of the ball of the node are co-planar, the sum of tensorial product of edges is non invertible (which makes sense because edges are prescribing a 0-length in the normal direction). In other cases, the length along the normal direction to the surface doesn't make sense physically. What we want is to compute the 2D size that is prescribed in the tangent plane. 
 
 Thus, for each point, if possible, the ball of point is processed : 
     - on a regular or required point, the ball of the point is projected onto its tangent plane and the anisotropic unit tensor is computed inside this plane in 2D, a hmax-like value is imposed in the third direction (if not provided, hmax is not yet computed at this point because it will be deduced from the edge sizes we are computing) and the 3D tensor is rotated back in the initial basis;

    - on a corner point, as the corner defines an angle, we should be able to compute directly a 3D tensor. It should allow to keep anisotropy (see the cube example) until reaching the call to defsiz and gradsiz after which size at corner points is isotropic. Computation is tested and if the resulting matrix is non invertible (normally it happens only if the corner is along a plane, for example at the intersection of more that 2 specific edges), we compute a normal at corner point from the triangles of the ball and we treat the corner as a regular point.

    - ridge manifold points are treated as the corners one (3D computation if possible, computation of the mean normal from the 2 normals at the point and projection onto the tangent plane and 2D computation otherwise).

    - along non-manifod points, the computation of the 3D tensor should always be possible. Such points are treated separately (we process edges of the mesh and add the contribution of each edge to its extremities if the extremity is a non-manifold point) because the ball of point can't be entirely and safely traveled (adjacency relationship of triangles is build in the order of numbering of triangles so if more than 2 surfaces are passing through a point, we only know that 2 triangles will have a filled adjaceny and the third one will have no ajdacency, but the filling may be non-consistent with the filling of the other triangles of the surface).

Capture d’écran 2022-08-24 à 11 02 32
In this test case, final mesh is less anisotropic that input one due to computation of the sizemap related to the hausdorff distance and the sizemap intersection (that impose a size in the normal direction of the boundaries).

Capture d’écran 2022-08-24 à 11 20 56

Capture d’écran 2022-08-24 à 12 21 44
In this case, corners became isotropic after the call to defsiz and the metric intersection.

Capture d’écran 2022-08-24 à 12 24 59

# mmg3d
Capture d’écran 2022-08-24 à 12 30 12
Capture d’écran 2022-08-24 à 12 30 22
Again, metric is less anisotropic in the volume close to the surface because along surface points, the metric is forced to have 2 main directions lying in the tangent plane and the third one along the normal direction to the surface.

Capture d’écran 2022-08-24 à 12 40 31
Capture d’écran 2022-08-24 à 12 40 54

### CODE REVIEW

**Comment by prj-** [comment]
This breaks ParMmg.
```
/usr/bin/ld: lib/libparmmg.so.1.4.0: undefined reference to `MMG5_solTruncatureForOptim'
```

**Comment by prj-** [comment]
The following patch works OK with anisotropic metrics, but fails with isotropic ones.
```diff
diff --git a/src/libparmmg.c b/src/libparmmg.c
index 28869d8..0621350 100644
--- a/src/libparmmg.c
+++ b/src/libparmmg.c
@@ -158,3 +158,11 @@ int PMMG_preprocessMesh( PMMG_pParMesh parmesh )
     }
-    MMG5_solTruncatureForOptim(mesh,met);
+    if ( met->size < 6 ) {
+      if ( !MMG5_solTruncature_iso(mesh,met) ) {
+        return PMMG_STRONGFAILURE;
+      }
+    } else {
+      if ( !MMG5_3dSolTruncature_ani(mesh,met) ) {
+        return PMMG_STRONGFAILURE;
+      }
+    }
   }
@@ -253,3 +261,11 @@ int PMMG_preprocessMesh_distributed( PMMG_pParMesh parmesh )
     }
-    MMG5_solTruncatureForOptim(mesh,met);
+    if ( met->size < 6 ) {
+      if ( !MMG5_solTruncature_iso(mesh,met) ) {
+        return PMMG_STRONGFAILURE;
+      }
+    } else {
+      if ( !MMG5_3dSolTruncature_ani(mesh,met) ) {
+        return PMMG_STRONGFAILURE;
+      }
+    }
   }
```
I don't see any comments about how you deprecated `MMG5_solTruncatureForOptim`, so it's kind of difficult for external users to follow your changes :/
Here is what I get, any idea on how to fix this?
```
Assertion failed: (mesh->point[k].flag < mesh->base), function MMG5_scale_scalarMetric, file scalem.c, line 204.
```

**Comment by Algiane** [comment]
Hi @prj- ,

Thank you for your help: indeed, as this function is not an API function, its deprecation has not be explained.

Your patch fails when checking that we can directly use the flag field of points as a marker to know if a point has been processed or not. This field has probably been used for something else in ParMmg: if it is not used anymore, the fix will be fast, if it is still used and must not been modified it can take a little more time.

I will keep you informed.
Best

**Comment by prj-** [comment]
They do indeed. Thank you.

**Pull request merged**
