### PR TITLE
Hotfix/parallel triangles modification

### PR DESCRIPTION
**Pull request by Algiane**
Points at the interface of a MG_BDY and a MG_PARBDY face where moving: we should skip MG_PARBDY points when seen from a non-required face but also MG_PARBDYBDY points.

### CODE REVIEW

**Comment by lcirrottola** [comment]
Thanks! Checking and testing in https://github.com/MmgTools/ParMmg/commit/502b512a24b621aa3142c6510eec1790a20bb2c2 (https://ci.inria.fr/parmmg/job/ParMmg-multiConf/569/) while reading the diff.

**Review by lcirrottola — CHANGES_REQUESTED** [review]
The MG_BDY tag can be used on parallel triangles.

All triangles are on a _mesh_ boundary, so the MG_BDY tag is indeed superfluous on the `MMG5_Tria objects` and it has been used in `ParMmg` to tag edges on a triangle on a _geometrical boundary_ (either an external boundary, or a an internal boundary which is also on a parallel interface) that are at the intersection with a _purely parallel_ triangle (i.e. not bringing any geometrical meaning).

**Comment by lcirrottola** [comment]
I understand the fix, but I don't get how a `MG_PARBDYBDY` point could not be `MG_PARBDY`, and it could be the symptom of another bug. 

My suspects:
- Originally the `MG_PARBDY` tag was passed from triangles to lower-dimensional entities, and `MG_PARBDYBDY` entities where also tagged hierachically from triangles.
- Later I fixed this behaviour to consider the case of a parallel surface "locally orthogonal" to a geometrical surface (i.e. with no triangles in their intersection, but only edges). So there can be edges that are `MG_PARBDYBDY` even if none of their supporting triangles is `MG_PARBDYBDY`.
- Still I don't get how a point could be `MG_PARBDYBDY`  while not `MG_PARBDY`...

How does the topology of the surface looks like in the proximity of the point?

**Comment by lcirrottola** [comment]
Thanks for the fix and the description! It is also consistent with 53156cbb338986a961c2b36eba2dac26fbb1b68a (for future reference).

**Comment by prj-** [comment]
Could you please merge the relevant commit in `develop` as well? Thanks!

**Pull request merged**
