### PR TITLE
Add support for SCOTCH 7

### PR DESCRIPTION
**Pull request by prj-**

### CODE REVIEW

**Comment by Algiane** [comment]
A very useful update, thanks!

**Comment by prudhomm** [comment]
@prj- see #328 
on recent ubuntu version(26.04) I get a linking failure 
```
libmmg2d.so: undefined reference to `_SCOTCHintSort2asc1'
clang: error: linker command failed with exit code 1
```
To support scotch 7 requires to stop  using `_SCOTCHintSort2asc1`, IMO. This is a internal function.

the function is called line 127 of src/common/librnbg.c
```c
_SCOTCHintSort2asc1(sortPartTb, vertNbr);
```

**Comment by prj-** [comment]
Not sure why we don't see this in PETSc.

**Comment by prudhomm** [comment]
indeed surprising, see a possible fix here #329

**Pull request merged**
