### PR TITLE
Feature/refactoring

### PR DESCRIPTION
**Pull request by lcirrottola**
- Refactor matrix algebra functions to have consistent versions and names in 2D and 3D.
- Add incremental unit tests for matrix eigendecomposition, (eigen)recomposition, simultaneous reduction, recomposition from simultaneous reduction, iterative metrics intersections, rotation matrix computation and linear transformation of a symmetric matrix.
- Fix product of two symmetric matrices that was causing the eigendecomposition to erroneously work on the transposed result (giving left eigenvectors instead of right eigenvectors).
- Fix computation of eigenvectors of a non-symmetric matrix when an eigenvalue has algebraic multiplicity 2 (test also in the symmetric case.

### CODE REVIEW

**Comment by lcirrottola** [comment]
Compilation fixed in https://ci.inria.fr/mmg/job/Mmg-multiConf/2858/.
@Algiane new eigenvectors computation tested also for the symmetric case in 21384aaeb7a7943085c48d37cdc09bf3a56478a0.

**Comment by lcirrottola** [comment]
Last tests should be https://ci.inria.fr/mmg/job/Mmg-multiConf/2862/.

**Comment by lcirrottola** [comment]
Now https://ci.inria.fr/mmg/job/Mmg-multiConf/2863/.

**Comment by Algiane** [comment]
Thanks for all this work Luca!

**Pull request merged**
