### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by manisandro**
Changes needed to get the package to compile on Fedora.

### CODE REVIEW

**Comment by Algiane** [comment]
Hi,

First, thank you for the escaping of the %!

I can't remove the inclusion of the mmgexterns.c file on MacOS without linker errors.
I have tested the "old" version on ubuntu and it seems to work too.
On which distribution and version do you have the error of "multiple definition symbols"?

Thank you by advance,
Algiane

**Comment by manisandro** [comment]
Hi
I'm building on Fedora Rawhide (gcc10).
Thanks
Sandro

**Comment by Algiane** [comment]
Hi @manisandro ,

Sorry  for the long delay (this issue went out of my mind with the Covid lockdown).
Adding the initialization of the function pointers seems to solve the issues with the Clang compilation (see #73). It is merged in the master branch now.

Thanks again for your contribution and have a nice day.

Algiane

**Comment by manisandro** [comment]
Thanks for the followup, a nice day to you too

**Pull request closed without merging**
