### PR TITLE
Install missing headers for ParMmg.

### PR DESCRIPTION
**Pull request by prj-**

### CODE REVIEW

**Comment by lcirrottola** [comment]
I'll merge in feature/mmg-install first to test more.

**Comment by prj-** [comment]
Of course! This is just to get the ball rolling, I'd be happy to make changes/adjustments should you want some :)

**Comment by prj-** [comment]
So, do I need to address issues on the branch `feature/mmg-install`, or could you consider merging it into develop @lcirrottola?

**Comment by lcirrottola** [comment]
Sorry I know I am being picky, but I prefer keeping it as a feature and addressing changes to CMakeList on `feature/mmg-install` before merging to develop.
I know also that we are both used to open sourcing our code, but please consider signing the CLA for future contributions :-)

**Comment by prj-** [comment]
Any update on this?

**Pull request merged**
