### PR TITLE
Fix Valgrind errors

### PR DESCRIPTION
**Pull request by prj-**
See the Valgrind log [without](https://github.com/MmgTools/mmg/files/8457254/dump.1095530.log) (resp. [with](https://github.com/MmgTools/mmg/files/8457253/dump_fix.1097073.log)) this fix.

### CODE REVIEW

**Comment by Algiane** [comment]
Hi @prj,

Thanks for pointing out these issues and for the proposition of correction: before merging it I want to understand why we are using this values unitialized (with the 0 initialization we will still have behaviour issues because we want to use the geometric values stored at points here...).
I am in vacations next week but I will look at this when I will get back to work.

Best regards,
Algiane

**Comment by prj-** [comment]
Right, this may not be the proper fix. But at least it's a band-aid that helps bypass Valgrind errors!

**Comment by Algiane** [comment]
Hi @prj- ,

I have committed another proposition of fix: I prefer to not initialize directly the value of stack variables as thanks to the feedbacks of users it can allow to detect bugs ;-). 
On my test case, the fix allows to remove the same valgrind errors as the variable initialization that you have proposed (I still have to understand why we end up on the unexpected test case at the origin of the error (and if we can handle this in a more robust way than it is done now).  

Please, let me know if the fix is ok for you.

Best Regards,
Algiane

**Comment by prj-** [comment]
It seems to fix the Valgrind errors, though I now have Mmg warnings. I can't really judge what is the lesser evil, it's a rather trivial problem, so hopefully a more robust solution is around the corner.

**Comment by Algiane** [comment]
Hi,
From my side the test case on which I have the issue (with mmg only, not mmg called by ParMmg) is not so simple: if you have a simple reproducer for Mmg, it can be very helpful.
Best

**Comment by prj-** [comment]
I guess if you have a simple way for me to dump all necessary data that are being passed from ParMmg to Mmg, I could use that in my reproducer which uses ParMmg for you to use in Mmg afterwards.

**Comment by prj-** [comment]
Actually, I can reproduce this on an even smaller problem, only with Mmg, though I'm not sure it is well-defined in that case.
```
$ /media/psf/repositories/petsc/arch-linux-c-debug-real/bin/mpiexec -n 1 ./ex60 -dm_plex_dim 3 -dm_plex_box_faces 3,3,3 -dm_plex_metric_target_complexity 100 -dm_adaptor mmg
Metric average L2 error: 0.0000%
  ## Warning: MMG5_interpreg_ani: 601: unexpected case (null normal), impossible interpolation.

  ## Warning: MMG5_movbdyregpt_ani: unable to compute optimal position for at least 1 point.
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Argument out of range
[0]PETSC ERROR: Adapted mesh does not have face tag 2
[...]
```

**Comment by Algiane** [comment]
Thanks @prj- ,

Finally I have used my reproducer to find the bug.
See issue #139 for a full description of the bug fix.
Thank you by advance for the feedback on your own test cases.

Best Regards,

**Comment by prj-** [comment]
I still get the same warnings with ParMmg, but maybe it's not related.

**Comment by Algiane** [comment]
Thanks for the feedback... it is weird, I may have missed another location of the code where a similar behaviour occurs...
A particularity of the call of Mmg through ParMmg is that, due to the mesh partitionning, we have lot of singularities and sharp angles along the parallel interfaces. Thus, it makes sense that ParMmg raises up such kind of bugs, rather rare when we start from 'good' meshes comming from mesh generators.

**Comment by Algiane** [comment]
Hi @prj- ,

I would like to merge the PR with the modifications added in the [`prj--jolivet/fix-valgrind`](https://github.com/MmgTools/mmg/tree/prj--jolivet/fix-valgrind) branch. Can I push the modifications directly in your repository ?

Thank you by advance,
A.

**Comment by prj-** [comment]
Sure thing!

**Comment by Algiane** [comment]
I don't have push access I think (I have an authentication error).

**Comment by prj-** [comment]
Everything is alright on my end.
Screenshot 2022-04-27 at 10 12 11 AM

**Comment by Algiane** [comment]
Ouch thanks! (it seems than an old git-lfs test has broken authentications in my local repository).

**Comment by prj-** [comment]
I'm not sure why there are 17 commits in the branch. Did you properly rebase on top of `MmgTools:develop`?

**Comment by Algiane** [comment]
I have copy-pasted the command line instructions of github which pull the PR in a branch created from the develop one.

I think that the develop branch of Mmg has been modified since the creation of the PR (with the integration of your other PR to support scotch 7 for example) so your PR has been pull on top of this modifications and I have simply pushed all the stuff...

I don't know how to fix this: please let me know the git command to type if you know what to do.

**Pull request merged**
