### PR TITLE
Feature/fix boulernm efficiency

### PR DESCRIPTION
**Pull request by Algiane**
This PR rewrites the `setVertexNmTag` (function that analysis the type of feature edges arriving through a non-required non-manifold point and set the suitable tag at point):
  - initial function was travelling the tetra vertices, selecting the edges of the ball of the vertex incident to the vertex and counting the feature edges (edges where hashed in a new hash table for each vertex to be uniquely added);
  - now we travel tetra edges and increment edge vertices counters depending on the type of the feature edges. Edges are hashed to be uniquely added. Then we travel the mesh points and set the suitable tags depending on the computed counters.
  
This PR removes the `boulernm` function.

### CODE REVIEW

**Comment by prj-** [comment]
@Algiane, this PR breaks ParMmg.
```
Undefined symbols for architecture arm64:
  "_MMG5_boulernm", referenced from:
      _PMMG_update_singul in analys_pmmg.c.o
```

**Comment by Algiane** [comment]
Thanks for this report. I will try to fix this as soon as possible (I am in business travel for now).

**Comment by Algiane** [comment]
Hi,
Thanks for your patience. I have merged a temporary fix in Mmg (see issue [#97 ](https://github.com/MmgTools/ParMmg/issues/97)).
I hope that it will work while we wait for a real solution to the problem.
Best

**Comment by prj-** [comment]
Yes, it does work, thanks.

**Comment by prj-** [comment]
Sorry, I spoke too soon. Though now ParMmg builds successfully, it fails a very basic FreeFEM test with the following error.
```
Assertion failed: (isfinite(dd)), function PMMG_hashNorver_normals, file analys_pmmg.c, line 990.
```

**Comment by Algiane** [comment]
Hi,

Sorry for that. I will try to find this issue before the summer hollidays.

Best

**Comment by prj-** [comment]
No problem, in the meantime, I'm sticking to commit `6824158449e57b46253b505d968b81f15fafc6a0` of Mmg. Let me know if you want me to try something that you cooked up, there is no hurry at all, I'll still be here _after_ the summer holidays :)

**Pull request merged**
